version: "3.3"

volumes:
  dbdata:
    driver_opts:
       type: none
       o: bind
       device: "${POSTGRESQL_DBDATA}"
#      type: nfs
#      o: "nfsvers=4,addr=nfs1.easypro,rw"
#      device: ":/easypro.easyiot.link/pgsql/data"
