version: "3.3"

volumes:
  data:
    driver_opts:
       type: none
       o: bind
       device: "${PGADMIN_DATA}"
#      type: nfs
#      o: "nfsvers=4,addr=nfs1.easypro,rw"
#      device: ":/easypro.easyiot.link/pgadmin4/data"
