version: "3.3"

volumes:
  setting:
    driver_opts:
       type: none
       o: bind
       device: "${TRAEFIK_SETTING}"
#      type: nfs
#      o: "nfsvers=4,addr=nfs1.easypro,rw"
#      device: ":/${TRAEFIKDOMAIN}/{STACKNAME}/setting"

  config:
    driver_opts:
       type: none
       o: bind
       device: "${TRAEFIK_CONFIG}"
#      type: nfs
#      o: "nfsvers=4,addr=nfs1.easypro,rw"
#      device: ":/${TRAEFIKDOMAIN}/dockerscript/traefik2nfs/base/config"
    
  logs:
    driver_opts:
       type: none
       o: bind
       device: "${TRAEFIK_LOGS}"
#      type: nfs
#      o: "nfsvers=4,addr=nfs1.easypro,rw"
#      device: ":/${TRAEFIKDOMAIN}/{STACKNAME}/config"
