version: "3.3"
services:
  traefik:
    ports:
      - "3000:3000"
      
      
volumes:
  setting:
    driver_opts:
       type: none
#       o: bind
#       device: "${TRAEFIK_SETTING}"
       type: nfs
       o: "nfsvers=4,addr=nfs1.easypro,rw"
       device: ":${TRAEFIK_NFS_SETTING}"

  config:
    driver_opts:
       type: none
#       o: bind
#       device: "${TRAEFIK_CONFIG}"
       type: nfs
       o: "nfsvers=4,addr=nfs1.easypro,rw"
       device: ":${TRAEFIK_NFS_CONFIG}"
    
  logs:
    driver_opts:
       type: none
#       o: bind
#       device: "${TRAEFIK_LOGS}"
       type: nfs
       o: "nfsvers=4,addr=nfs1.easypro,rw"
       device: ":${TRAEFIK_NFS_LOGS}"
