volumes:
  data:
    driver_opts:
       type: none
       o: bind
       device: "${DATAPATH}/${STACKNAME}/data"
#      type: nfs
#      o: "nfsvers=4,addr=nfs1.easypro,rw"
#      device: ":/${TRAEFIKDOMAIN}/traefik/setting"

